import type {Metadata} from "next";
import {ReactNode} from "react";
import ThemeRegistry from "@/styles/theme-registry";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en">
        <ThemeRegistry>
            <body style={{margin: 0, padding: 0}}>
            {children}
            </body>
        </ThemeRegistry>
        </html>
    );
}
