import type {Metadata} from "next";
import {ReactNode} from "react";
import {AppRouterCacheProvider} from "@mui/material-nextjs/v13-appRouter";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en">
        <AppRouterCacheProvider>
            <body style={{margin: 0, padding: 0}}>
            {children}
            </body>
        </AppRouterCacheProvider>
        </html>
    );
}
