import type { Metadata } from "next";
import { ReactNode } from "react";
import ThemeRegistry from "@/styles/theme-registry";
import "swiper/css";
import { Box } from "@mui/material";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeRegistry>
        <Box component={"body"}>{children}</Box>
      </ThemeRegistry>
    </html>
  );
}
